# Generated by Django 2.2.24 on 2021-09-08 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocuSignAPIKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=250, verbose_name='DocuSign User ID')),
                ('account_id', models.CharField(max_length=250, verbose_name='DocuSign Account ID')),
                ('integration_key', models.CharField(max_length=250, verbose_name='DocuSign INTEGRATION KEY')),
                ('rsa_public_key', models.TextField(verbose_name='RSA PUBLIC KEY')),
                ('rsa_private_key', models.TextField(verbose_name='RSA PUBLIC KEY')),
                ('keypair_id', models.CharField(max_length=250, verbose_name='key Pair ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'DocuSign API Key',
                'verbose_name_plural': 'DocuSign API keys',
                'ordering': ('-created',),
            },
        ),
    ]
