# Generated by Django 2.2.24 on 2021-09-08 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docusignapikey',
            name='rsa_private_key_file',
            field=models.FileField(null=True, upload_to='documents/docusign'),
        ),
    ]
