# Generated by Django 2.2.24 on 2021-09-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20210908_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='docusignapikey',
            name='auth_server_http',
            field=models.URLField(blank=True, null=True),
        ),
    ]
