# Generated by Django 2.2.24 on 2021-09-13 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_auto_20210908_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='docusignapikey',
            name='scopes',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
