# Generated by Django 2.2.24 on 2021-09-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_docusignapikey_scopes'),
    ]

    operations = [
        migrations.AddField(
            model_name='docusignapikey',
            name='secret_key',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='docusignapikey',
            name='rsa_private_key_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/docusign'),
        ),
    ]
