# Generated by Django 2.2.24 on 2021-09-16 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0007_auto_20210913_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signer_email', models.EmailField(max_length=254, verbose_name='Signer email')),
                ('signer_name', models.EmailField(max_length=254, verbose_name='Signer Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/envelops', verbose_name='File')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sign_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document For Sign',
                'verbose_name_plural': 'Document For Sign',
                'ordering': ('-created',),
            },
        ),
    ]
