# Generated by Django 2.2.24 on 2021-09-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_documentsign'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentsign',
            options={'ordering': ('-created',), 'verbose_name': 'Document For Sign', 'verbose_name_plural': 'Documents For Sign'},
        ),
        migrations.AlterField(
            model_name='documentsign',
            name='signer_name',
            field=models.CharField(max_length=50, verbose_name='Signer Name'),
        ),
    ]
