# Generated by Django 2.2.24 on 2021-09-16 14:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0009_auto_20210916_2004'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DocumentSign',
            new_name='DocumentSignEnvelope',
        ),
    ]
