# Generated by Django 2.2.24 on 2021-09-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_auto_20210916_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsignenvelope',
            name='envelope_id',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Envelope ID'),
        ),
    ]
