# Generated by Django 2.2.24 on 2021-11-05 05:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0012_documentsignenvelope_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsignenvelope',
            name='sign_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documentsignenvelope',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/envelops', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='documentsignenvelope',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_document_sign_envelopes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='docusignapikey',
            name='rsa_private_key',
            field=models.TextField(verbose_name='RSA Private KEY'),
        ),
    ]
