# Generated by Django 2.2.24 on 2021-11-05 23:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_auto_20211105_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsignenvelope',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/envelops', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx'])], verbose_name='File'),
        ),
    ]
